<?php
/**
 * WeCodeArt Framework.
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package 	WeCodeArt Framework.
 * @subpackage  WeCodeArt/Config/Exceptions/FileNotFoundException
 * @copyright   Copyright (c) 2021, WeCodeArt Framework
 * @since		3.9.5
 * @version		3.9.5
 */

namespace WeCodeArt\Config\Exceptions;
use Exception;

/**
 * FileNotFoundException.
 *
 * @author     Bican Marian Valeriu <marianvaleriubican@gmail.com>
 */
class FileNotFoundException extends Exception {}