<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Gutenberg\Blocks
 * @copyright   Copyright (c) 2021, WeCodeArt Framework
 * @since		5.2.2
 * @version		5.2.2
 */

namespace WeCodeArt\Gutenberg\Blocks\Comment;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Markup;
use WeCodeArt\Markup\SVG;
use WeCodeArt\Singleton;
use WeCodeArt\Gutenberg\Blocks\Dynamic;
use function WeCodeArt\Functions\get_prop;

/**
 * Gutenberg Comment Form block.
 */
class Form extends Dynamic {

	use Singleton;

	/**
	 * Block namespace.
	 *
	 * @var string
	 */
	protected $namespace = 'core';

	/**
	 * Block name.
	 *
	 * @var string
	 */
	protected $block_name = 'post-comments-form';

	/**
	 * Shortcircuit Register
	 */
	public function register() {
		add_filter( 'comment_form_fields',		[ $this, 'comment_form_fields' 		], 90 );
		add_filter( 'comment_form_defaults',	[ $this, 'comment_form_defaults' 	], 90 );
		add_action( 'pre_comment_on_post',  	[ $this, 'validate_cookies'			] );
	}

	/**
	 * Move Comment Field Bellow Name/Email/Website.
	 *
	 * @since	unknown
	 * @version 5.0.0
	 *
	 * @param 	array $fields
	 *
	 * @return 	array
	 */
	public function comment_form_fields( $fields ) {
		$comment_field = $fields['comment'];
		$cookies_field = $fields['cookies'];
		unset( $fields['comment'], $fields['cookies'] );
		
		$fields['comment'] = $comment_field;
		$fields['cookies'] = $cookies_field;
		return $fields;
	}

	/**
	 * Filter Comment Respond Args.
	 *
	 * @since	unknown
	 * @version	5.2.2
	 *
	 * @return 	array
	 */
	public function comment_form_defaults( $defaults ) {
		$dots_1 = SVG::compile( 'comment-dots', [ 'class' => 'fa-2x me-2' ] );
		$dots_2 = SVG::compile( 'comment-dots', [ 'class' => 'me-1' ] );

		return wp_parse_args( [
			'format'			 	=> 'html5',
			'class_container'		=> 'wp-block-post-comments-form__wrap',
			'class_form' 			=> 'wp-block-post-comments-form__form comment-form needs-validation',
			'title_reply' 			=> $dots_1 . esc_html__( 'Speak Your Mind', 'wecodeart' ),
			'title_reply_before' 	=> '<h3 class="wp-block-post-comments-form__headline" id="reply-title">',
			'title_reply_after'  	=> '</h3>',
			'cancel_reply_before'  	=> '<span class="has-small-font-size my-2 float-end">',
			'cancel_reply_after'   	=> '</span>',
			'cancel_reply_link'    	=> esc_html__( 'Cancel reply', 'wecodeart' ),
			'comment_field' 		=> $this->get_input( 'comment' ),
			'comment_notes_before' 	=> $this->get_form_notes(),
			'submit_field'			=> '<div class="mb-3 comment-form-submit">%1$s %2$s</div>',
			'submit_button'			=> '<button name="%1$s" type="submit" id="%2$s" class="%3$s">' . $dots_2 . '<span>%4$s</span></button>',
			'class_submit'			=> 'btn btn-outline-dark',
			'fields' 				=> [
				'author' 	=> $this->get_input( 'name' ),
				'email'  	=> $this->get_input( 'email' ),
				'url'    	=> $this->get_input( 'url' ),
				'cookies'	=> $this->get_input( 'cookies' ),
			]
		], $defaults );
	}

	/**
	 * Get Name Input
	 *
	 * @since	5.2.2
	 * @since	5.2.2
	 *
	 * @return 	void
	 */
	public function get_input( $type = '' ) {
		$commenter = wp_get_current_commenter();
		$req       = get_option( 'require_name_email' );

		switch( $type ) {
			case 'name':
				return Markup::wrap( 'comment-author-name', [ [
					'tag' 	=> 'div',
					'attrs' => [
						'class' => 'mb-3 comment-form-author col-md-7'
					]
				] ], 'wecodeart_input', [ 'floating', [
					'type' 	=> 'text',
					'label' => esc_html__( 'Name *', 'wecodeart' ),
					'attrs' => [
						'id' 	=> 'comment-author',
						'name' 	=> 'author',
						'size' 			=> 30,
						'maxlength' 	=> 245,
						'placeholder'	=> 'John Doe',
						'value' 		=> $commenter['comment_author'],
						'required' 		=> ( $req ) ? 'required' : NULL,
					]
				] ], false );
			break;

			case 'email':
				return Markup::wrap( 'comment-author-email', [ [
					'tag' 	=> 'div',
					'attrs' => [
						'class' => 'mb-3 comment-form-email col-md-7'
					]
				] ], 'wecodeart_input', [ 'floating', [
					'type' 	=> 'email',
					'label' => esc_html__( 'Email *', 'wecodeart' ),
					'attrs' => [
						'id' 	=> 'comment-email',
						'name' 	=> 'email',
						'size' 			=> 30,
						'maxlength' 	=> 100,
						'placeholder'	=> 'name@example.com',
						'value' 		=> $commenter['comment_author_email'],
						'required' 		=> ( $req ) ? 'required' : NULL,
					]
				] ], false );
			break;

			case 'url':
				return Markup::wrap( 'comment-author-url', [ [
					'tag' 	=> 'div',
					'attrs' => [
						'class' => 'mb-3 comment-form-url col-md-7'
					]
				] ], 'wecodeart_input', [ 'floating', [
					'type' 	=> 'url',
					'label' => esc_html__( 'Website', 'wecodeart' ),
					'attrs' => [
						'id' 	=> 'comment-url',
						'name' 	=> 'url',
						'size' 		 => 30, 
						'maxlength'  => 200,
						'placeholder'=> 'www.example.com',
						'value' 	 => $commenter['comment_author_url'] ,
					]
				] ], false );
			break;

			case 'comment':
				return Markup::wrap( 'comment-author-comment', [ [
					'tag' 	=> 'div',
					'attrs' => [
						'class' => 'mb-3 comment-form-comment'
					]
				] ], 'wecodeart_input', [ 'floating', [
					'type'	=> 'textarea',
					'label' => esc_html__( 'Comment *', 'wecodeart' ),
					'attrs' => [
						'id' 	=> 'comment',
						'name' 	=> 'comment',
						'rows'	=> 8,
						'cols'  => 45,
						'style'	=> 'min-height:150px;',
						'placeholder'	=> esc_html__( 'Comment *', 'wecodeart' ),
						'required'		=> ( $req ) ? 'required' : NULL,
					]
				] ], false );
			break;

			case 'cookies':
				$content = '';
				$privacy = get_option( 'wp_page_for_privacy_policy' );

				if( (bool) $privacy && get_post_status( $privacy ) === 'publish' ) {
					$permalink = sprintf(
						'<a href="%1$s">%2$s</a>',
						esc_url( get_privacy_policy_url() ),
						esc_html( get_the_title( $privacy ) )
					);
					
					$content = Markup::wrap( 'comment-cookies', [ [
						'tag' 	=> 'div',
						'attrs' => [
							'class' => 'mb-3 comment-form-cookies'
						]
					] ], 'wecodeart_input', [ 'toggle', [
						'type'	=> 'checkbox',
						'label' => sprintf( __( 'By commenting you accept the %s.', 'wecodeart' ), $permalink ),
						'attrs' => [
							'class'		=> 'form-switch',
							'id' 		=> 'comment-cookies',
							'name' 		=> 'comment-cookies',
							'required'  => ( $req ) ? 'required' : NULL,
						]
					] ], false );
				}

				return $content;
			break;

			default:
				return '';
		}
	}

	/**
	 * Get Form Notes
	 *
	 * @since	5.2.2
	 * @since	5.2.2
	 *
	 * @return 	void
	 */
	public function get_form_notes() {
		return Markup::wrap( 'comment-notes-before', [ [
			'tag' 	=> 'div',
			'attrs' => [
				'class' => 'mb-3 comment-form-notes'
			]
		] ], function() {

			$string = esc_html__( 'Your email address will not be published.', 'wecodeart' );

			if( get_option( 'require_name_email' ) ) {
				$string .= ' ' . sprintf( esc_html__( 'Required fiels are marked "%s".', 'wecodeart' ), 
					'<span class="required text-danger">*</span>' 
				);
			}

			echo wp_kses_post( $string );

		}, [], false );
	}

	/**
	 * Validate Cookie field.
	 *
	 * @since	5.0.0
	 * @since	5.0.5
	 *
	 * @return 	void
	 */
	public function validate_cookies() {
		$privacy = get_option( 'wp_page_for_privacy_policy' );

		if( get_post_status( $privacy ) !== 'publish' || is_user_logged_in() === false ) return;

		if( ! filter_input( INPUT_POST, 'comment-cookies' ) ) {
			wp_die( sprintf( esc_html__( 'You must accept %s to comment!', 'wecodeart' ), sprintf(
				'<a href="%1$s" target="_blank">%2$s</a>',
				esc_url( get_privacy_policy_url() ),
				esc_html( get_the_title( $privacy ) )
			) ) );
		}
	}
}
