<?php
/**
 * WeCodeArt Framework.
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package 	WeCodeArt Framework
 * @subpackage 	Sidebar PHP
 * @since 		v1.0
 * @version		v3.0.8
 */

if ( ! class_exists( 'wecodeart_sidebar_dummy' ) ) {
	class wecodeart_sidebar_dummy {
		// Silence is golden !
	}
}