<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Gutenberg\Blocks
 * @copyright   Copyright (c) 2021, WeCodeArt Framework
 * @since		5.0.0
 * @version		5.0.0
 */

namespace WeCodeArt\Gutenberg\Blocks\Text;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Markup;
use WeCodeArt\Singleton;
use WeCodeArt\Gutenberg\Blocks\Dynamic;
use function WeCodeArt\Functions\get_prop;

/**
 * Gutenberg Pullquote block.
 */
class Pullquote extends Dynamic {

	use Singleton;

	/**
	 * Block namespace.
	 *
	 * @var string
	 */
	protected $namespace = 'core';

	/**
	 * Block namespace.
	 *
	 * @var string
	 */
	protected $block_name = 'pullquote';

	/**
	 * Shortcircuit Register
	 */
	public function register_block_type() {
		add_filter( 'render_block_core/pullquote', [ $this, 'render' ], 10, 2 );
	}

	/**
	 * Dynamically renders the `core/pullquote` block.
	 *
	 * @param 	string 	$content 	The block markup.
	 * @param 	array 	$block 		The parsed block.
	 *
	 * @return 	string 	The block markup.
	 */
	public function render( $content = '', $block = [], $data = null ) {
		$this->enqueue_styles();

		return $content;
	}

	/**
	 * Block styles
	 *
	 * @return 	string 	The block styles.
	 */
	public function styles( $attributes = [] ) {
		return "
		.wp-block-pullquote {
			padding: 3rem 0;
			text-align: center;
			border-top-width: 5px;
			border-bottom-width: 5px;
			border-top-style: solid;
			border-bottom-style: solid;
		}
		.wp-block-pullquote.is-style-solid-color {
			border-width: 0;
			border-style: none;
		}
		.wp-block-pullquote.is-style-solid-color blockquote {
			margin: 0 auto 0;
			text-align: left;
			max-width: max( 400px, 60% );
		}
		.wp-block-pullquote.is-style-solid-color blockquote p {
			font-size: 2.5rem;
			margin-bottom: 0;
		}
		.wp-block-pullquote	blockquote {
			margin-bottom: 0;
			padding: 0 1rem;
		}
		.wp-block-pullquote p {
			margin-bottom: 0;
			font-size: 1.5rem;
		}
		";
	}
}
