<?php namespace WeCodeArt\Core;
// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) exit(); 
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package 	WeCodeArt Framework
 * @subpackage 	WeCodeArt\Core\Callbacks
 * @since 		v3.5
 * @version		v3.5
 */

class Callbacks {
	/**
	 * Instance
	 *
	 * @access 	private
	 * @var 	object
	 */
	private static $instance;

	/**
	 * Initiator
	 */
	public static function get_instance() {
		if ( ! isset( self::$instance ) ) self::$instance = new self;
		return self::$instance;
	}

	public function __construct() {}

	/**
	 * Checks if the current page is a product archive
	 * @since	v1.8.8
	 * @version	v3.5
	 */
	public static function _is_frontpage() {
		return( is_front_page() && ! is_home() );
	}
}