<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Gutenberg CSS Frontend
 * @copyright   Copyright (c) 2023, WeCodeArt Framework
 * @since		5.0.0
 * @version		5.7.2
 */

namespace WeCodeArt\Gutenberg\Modules\Styles\Blocks;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Singleton;
use WeCodeArt\Gutenberg\Modules\Styles\Blocks as Base;
use function WeCodeArt\Functions\get_prop;

/**
 * Block CSS Processor
 */
class Spacer extends Base {
	/**
	 * Parses an output and creates the styles array for it.
	 *
	 * @return 	void
	 */
	protected function process_extra(): void {	
		$output	= [
			'element' => $this->get_selector()
		];

		// Height
		if ( $value = get_prop( $this->attrs, 'height', '100px' ) ) {
			// Mobile Spacer can be reduced using custom CSS variable
			array_unshift( $this->output, wp_parse_args( [
				'property' 	=> '--wp--spacer-height',
				'value'	  	=> $value,
			], $output ) );
		}
		
		// Width
		if ( $value = get_prop( $this->attrs, 'width' ) ) {
			// Mobile Spacer can be reduced using custom CSS variable
			array_unshift( $this->output, wp_parse_args( [
				'property' 	=> '--wp--spacer-width',
				'value'	  	=> $value,
			], $output ) );
		}
	}
}