<?php
/**
 * WeCodeArt Framework.
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package 	WeCodeArt Framework
 * @subpackage  Header Woo Cart
 * @since	 	4.0.7
 * @version    	4.0.7
 */

defined( 'ABSPATH' ) || exit();

/**
 * @see     WeCodeArt\Support\WooCommerce\display_cart_module
 * @param   string $subtotal    Escaped above - wp_kses_post
 */
?>
<span class="header-bar__cart-subtotal"><?php echo wp_kses_post( $subtotal ); ?></span>