<?php
/**
 * WeCodeArt Framework.
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package 	WeCodeArt Framework
 * @subpackage  Header Logo HTML
 * @since	 	5.0.0
 * @version    	5.0.0
 */

defined( 'ABSPATH' ) || exit();

?>
<a class="d-block my-2" href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home">
	<?php

	// Title
	printf(
		'<%1$s class="site-title fw-bold fs-6 text-uppercase mb-0">%2$s</%1$s>',
		is_front_page() ? 'h1' : 'p',
		get_bloginfo( 'name' ) 
	);

	// Description
	$description = get_bloginfo( 'description', 'display' );
	if ( $description ) : ?>
	<p class="site-description fs-6 mb-0"><?php echo wp_kses_post( $description ); ?></p><?php
	endif;

	?>
</a>