<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Styles\Components
 * @copyright   Copyright (c) 2023, WeCodeArt Framework
 * @since		6.2.8
 * @version		6.2.8
 */

namespace WeCodeArt\Support\Styles\Components;

defined( 'ABSPATH' ) || exit();

use function WeCodeArt\Functions\get_prop;

/**
 * Parallax Styles
 */
class Parallax extends Base {
	/**
     * Component's Style Deps.
     *
     * @var     array
     */
    static $deps = [];

    /**
	 * Component styles.
	 *
	 * @return 	string
	 */
	public static function styles(): string {
		$inline = '
			.has-parallax {
				--wp--animation: parallaxBackground;
				--wp--easing: linear;
				--wp--range: 0vh, 100vh;
				--wp--offset: -250px;
				animation-name: var(--wp--animation);
				animation-duration: 1ms;
				animation-timing-function: var(--wp--easing);
				animation-timeline: scroll();
				animation-range: var(--wp--range);
			}
			
			@keyframes parallaxBackground {
				to {
					background-position: 50% calc(50% + var(--wp--offset));
				}
			}
        ';

		return $inline;
	}
}
