<?php
/**
 * WeCodeArt Framework.
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package 	WeCodeArt Framework
 * @subpackage 	WeCodeArt\Config\Traits
 * @copyright   Copyright (c) 2025, WeCodeArt Framework
 * @since 		4.0
 * @version		6.3.7
 */

namespace WeCodeArt\Config\Traits;

defined( 'ABSPATH' ) || exit; 

/**
 * Trait for integrations that do not have any conditionals.
 */
trait No_Conditionals {

	/**
	 * Returns an empty array, meaning no conditionals are required to load whatever uses this trait.
	 *
	 * @return array The conditionals that must be met to load this.
	 */
	public static function get_conditionals() {
		return [];
	}
}