<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Gutenberg\Blocks
 * @copyright   Copyright (c) 2023, WeCodeArt Framework
 * @since		5.0.0
 * @version		5.7.2
 */

namespace WeCodeArt\Gutenberg\Blocks\Navigation;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Singleton;
use WeCodeArt\Gutenberg\Blocks\Dynamic;
use WeCodeArt\Gutenberg\Blocks\Navigation\Link;

/**
 * Gutenberg Navigation Submenu block.
 */
class Menu extends Dynamic {

	use Singleton;

	/**
	 * Block namespace.
	 *
	 * @var string
	 */
	protected $namespace = 'core';

	/**
	 * Block name.
	 *
	 * @var string
	 */
	protected $block_name = 'navigation-submenu';

	/**
	 * Shortcircuit Register
	 */
	public function register() {
		\add_filter( 'block_type_metadata_settings', [ $this, 'filter_render' ], 10, 2 );
	}

	/**
	 * Filter submenu markup
	 *
	 * @param	array 	$settings
	 * @param	array 	$data
	 */
	public function filter_render( $settings, $data ) {
		if ( $this->get_block_type() === $data['name'] ) {
			$settings = wp_parse_args( [
				'render_callback' => [ Link::get_instance(), 'render' ]
			], $settings );
		}
		
		return $settings;
	}

	/**
	 * Block styles
	 *
	 * @return 	string 	The block styles.
	 */
	public function styles(): string {
		$inline = '';

		$inline .= "
			/* Dropdowns */
			.dropup,
			.dropend,
			.dropdown,
			.dropstart {
				position: relative;
			}
			.dropdown-toggle {
				white-space: nowrap;
			}
			.dropdown-toggle::after {
				content: '';
				display: inline-block;
				margin-left: .5em;
				vertical-align: 0.125em;
				border-top: 0.3em solid;
				border-left: 0.3em solid transparent;
				border-right: 0.3em solid transparent;
				border-bottom: 0;
			}
			.dropdown-toggle:empty::after {
				margin-left: 0;
			}
			.dropdown-menu {
				--wp--dropdown-zindex: 1000;
				--wp--dropdown-min-width: 10rem;
				--wp--dropdown-padding-x: 0;
				--wp--dropdown-padding-y: 0.5rem;
				--wp--dropdown-spacer: 0;
				--wp--dropdown-color: var(--wp--preset--color--dark);
				--wp--dropdown-bg: var(--wp--white);
				--wp--dropdown-border-width: 1px;
				--wp--dropdown-border-color: var(--wp--gray-200);
				--wp--dropdown-border-radius: 0.375rem;
				--wp--dropdown-divider-bg: rgba(0,0,0, .05);
				--wp--dropdown-divider-margin-y: 0.5rem;
				--wp--dropdown-box-shadow: 0 0.5rem 1rem rgba(0,0,0, 0.15);
				--wp--dropdown-link-color: var(--wp--preset--color--dark);
				--wp--dropdown-link-hover-color: var(--wp--preset--color--dark);
				--wp--dropdown-link-hover-bg: var(--wp--preset--color--light);
				--wp--dropdown-link-active-color: var(--wp--white);
				--wp--dropdown-link-active-bg: var(--wp--preset--color--primary);
				--wp--dropdown-link-disabled-color: var(--wp--gray-400);
				--wp--dropdown-item-padding-x: 1rem;
				--wp--dropdown-item-padding-y: 0.25rem;
				--wp--dropdown-header-color: var(--wp--gray-600);
				--wp--dropdown-header-padding-x: 1rem;
				--wp--dropdown-header-padding-y: 0.5rem;
				position: absolute;
				display: none;
				z-index: var(--wp--dropdown-zindex);
				min-width: var(--wp--dropdown-min-width);
    			padding: var(--wp--dropdown-padding-y) var(--wp--dropdown-padding-x);
				margin: 0;
				text-align: left;
				list-style: none;
				color: var(--wp--dropdown-color);
				background-color: var(--wp--dropdown-bg);
				border: var(--wp--dropdown-border-width) solid var(--wp--dropdown-border-color);
    			border-radius: var(--wp--dropdown-border-radius);
			}
			.dropdown-menu[data-bs-popper] {
				top: 100%;
				left: 0;
				margin-top: var(--wp--dropdown-spacer);
			}
			.dropdown-menu-start {
				--wp--position: start;
			}
			.dropdown-menu-start[data-bs-popper] {
				right: auto;
				left: 0;
			}
			.dropdown-menu-end {
				--wp--position: end;
			}
			.dropdown-menu-end[data-bs-popper] {
				right: 0;
				left: auto;
			}
		";

		// Temporary Disable unnecessary styles until we implement something
		if( false ) { 
			$inline .= "
				.dropup .dropdown-menu[data-bs-popper] {
					top: auto;
					bottom: 100%;
					margin-top: 0;
					margin-bottom: 0.125rem;
				}
				.dropup .dropdown-toggle::after {
					content: '';
					display: inline-block;
					margin-left: 0.255em;
					vertical-align: 0.255em;
					border-top: 0;
					border-right: 0.3em solid transparent;
					border-bottom: 0.3em solid;
					border-left: 0.3em solid transparent;
				}
				.dropup .dropdown-toggle:empty::after {
					margin-left: 0;
				}
				.dropend .dropdown-menu[data-bs-popper] {
					top: 0;
					right: auto;
					left: 100%;
					margin-top: 0;
					margin-left: 0.125rem;
				}
				.dropend .dropdown-toggle::after {
					content: '';
					display: inline-block;
					margin-left: 0.255em;
					vertical-align: 0.255em;
					border-top: 0.3em solid transparent;
					border-right: 0;
					border-bottom: 0.3em solid transparent;
					border-left: 0.3em solid;
				}
				.dropend .dropdown-toggle:empty::after {
					margin-left: 0;
				}
				.dropend .dropdown-toggle::after {
					vertical-align: 0;
				}
				.dropstart .dropdown-menu[data-bs-popper] {
					top: 0;
					right: 100%;
					left: auto;
					margin-top: 0;
					margin-right: 0.125rem;
				}
				.dropstart .dropdown-toggle::after {
					content: '';
					display: inline-block;
					margin-left: 0.255em;
					vertical-align: 0.255em;
				}
				.dropstart .dropdown-toggle::after {
					display: none;
				}
				.dropstart .dropdown-toggle::before {
					content: '';
					display: inline-block;
					margin-right: 0.255em;
					vertical-align: 0.255em;
					border-top: 0.3em solid transparent;
					border-right: 0.3em solid;
					border-bottom: 0.3em solid transparent;
				}
				.dropstart .dropdown-toggle:empty::after {
					margin-left: 0;
				}
				.dropstart .dropdown-toggle::before {
					vertical-align: 0;
				}
			";
		}

		$inline .= "
			.wp-block-navigation .dropdown-item {
				display: block;
				width: 100%;
				padding: var(--wp--dropdown-item-padding-y) var(--wp--dropdown-item-padding-x);
				color: var(--wp--dropdown-link-color);
				font-weight: inherit;
				text-align: inherit;
				white-space: nowrap;
				background-color: transparent;
				border: 0;
				border-radius: var(--wp--dropdown-item-border-radius,0);
				clear: both;
			}
			.wp-block-navigation .dropdown-item:is(:hover,:focus) {
				color: var(--wp--dropdown-link-hover-color);
    			background-color: var(--wp--dropdown-link-hover-bg);
			}
			.wp-block-navigation .dropdown-item:is(.active,:active) {
				color: var(--wp--dropdown-link-active-color);
				background-color: var(--wp--dropdown-link-active-bg);
				text-decoration: none;
			}
			.wp-block-navigation .disabled>.dropdown-item,
			.wp-block-navigation .dropdown-item:is(.disabled,:disabled) {
				color: var(--wp--dropdown-link-disabled-color);
				pointer-events: none;
				background-color: transparent;
			}
			.wp-block-navigation .dropdown-menu.show {
				display: block;
			}

			/* Elements */
			.wp-block-navigation .dropdown-header {
				padding: var(--wp--dropdown-header-padding-y) var(--wp--dropdown-header-padding-x);
				margin-bottom: 0;
				color: var(--wp--dropdown-header-color);
				font-size: var(--wp--preset--font-size--small);
				white-space: nowrap;
			}
			.wp-block-navigation .dropdown-text,
			.wp-block-navigation .dropdown-item-text {
				display: block;
				padding: var(--wp--dropdown-header-padding-y) var(--wp--dropdown-header-padding-x);
				color: var(--wp--dropdown-color);
			}
			.wp-block-navigation .dropdown-divider {
				height: 0;
				margin: var(--wp--dropdown-divider-margin-y) 0;
				border-top: 1px solid var(--wp--dropdown-divider-bg);
				overflow: hidden;
			}
			
			/* Dark */
			.wp-block-navigation .dropdown-menu-dark {
				--wp--dropdown-color: var(--wp--gray-500);
				--wp--dropdown-bg: #343a40;
				--wp--dropdown-border-color: rgba(255,255,255, .15);
				--wp--dropdown-divider-bg: rgba(255,255,255, .15);
				--wp--dropdown-link-color: var(--wp--gray-500);
				--wp--dropdown-link-hover-color: var(--wp--white);
				--wp--dropdown-link-hover-bg: rgba(255,255,255, .15);
				--wp--dropdown-link-active-color: var(--wp--white);
				--wp--dropdown-link-active-bg: var(--wp--preset--color--primary);
				--wp--dropdown-link-disabled-color: var(--wp--gray-600);
				--wp--dropdown-header-color: var(--wp--gray-500);
			}

			/* Block */
			.wp-block-navigation.hide-toggle .dropdown-toggle::after {
				content: none;
			}
			.wp-block-navigation.with-hover .dropdown:where(:hover,:focus,:focus-within) > .dropdown-toggle ~ .dropdown-menu {
				display: block;
				visibility: visible;
				opacity: 1;
			}
			.wp-block-navigation .dropdown-menu .dropdown-menu {
				top: 0;
				left: 100%;
			}
		";

		return $inline;
	}
}